version: '3'

services:
  db:
    image: mongo:latest
    restart: always
    volumes:
      - /Users/caspar/dev/temp200423/air-quality/db:/Users/caspar/dev/temp200423/air-quality/data/db
    ports:
      - 27017:27017
      
  server:
    build: ./server
    restart: always
    ports:
      - 80:3000
      
  worker:
    build: ./worker
    restart: always