version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always
    volumes: 
      - /opt/airquality/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 3001:8081

  server:
    build: .
    restart: always
    ports:
      - 80:3000
