version: '3'

services:
  db:
    image: mongo:latest
    restart: always
    volumes:
      - /opt/airquality/db:/data/db
    ports:
      - 27017:27017
      
  server:
    build: ./server
    restart: always
    ports:
      - 80:3000
    environment:
      - SCS_KEY
      
  worker:
    build: ./worker
    restart: always
    environment:
      - SCS_KEY